version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
build:
  publish_nuget: true
  parallel: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: eQ6skBTftegTPvdpfLmxICWF0LsK4VJlaStB5N+jBFJZ7ev12JV7moPqt7ajaPNr
  skip_symbols: true
  artifact: /.*\.nupkg/