version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
build:
  publish_nuget: true
  parallel: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: V/7U2DZSaG6WgG1mGQ5ZMPZuYIRKXO0g0I3Lkrv9SzTTydN2VDLjNHU3dse/vsQDLqftnq8g040PTMypsn3fuC1p55ekSfK5z+51ElQ1C+0=
  skip_symbols: true
  artifact: /.*\.nupkg/